OBJECTS = $(DIR_O)/str_func.o $(DIR_O)/str_input.o $(DIR_O)/main.o $(DIR_O)/func_sort.o 
CC = g++
CFLAGS = -c -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE -D DEBUG_MODE
DIR_O = object
DIR_SOUR = source

kotik.exe: $(OBJECTS)
	$(CC) $(OBJECTS)  -o object/kotik.exe
	
$(DIR_O)/str_func.o: $(DIR_SOUR)/str_func.cpp $(DIR_SOUR)/use_me_and_live_without_errors.h
	$(CC) $(CFLAGS) $< -o $@

$(DIR_O)/main.o: $(DIR_SOUR)/main.cpp $(DIR_SOUR)/test.h $(DIR_SOUR)/quad_equ.h $(DIR_SOUR)/debug_and_logs.h $(DIR_SOUR)/use_me_and_live_without_errors.h
	$(CC) $(CFLAGS) $< -o $@

$(DIR_O)/quad_equ.o: $(DIR_SOUR)/quad_equ.cpp $(DIR_SOUR)/input_or_output.h $(DIR_SOUR)/debug_and_logs.h $(DIR_SOUR)/comp_double.h $(DIR_SOUR)/quad_equ.h $(DIR_SOUR)/use_me_and_live_without_errors.h
	$(CC) $(CFLAGS) $< -o $@